### PR TITLE
Chunky png

### PR DESCRIPTION
**Pull request by mmolhoek**
This is just a test setup :), but it is working for me.
I will be building a more official gem myself, but as i need some time to set that up and as you maybe want to play with it, here it is

read the readme to see how you use it

### CODE REVIEW

**Comment by mmolhoek** [comment]
mmm, don't know why all your commits are here as well, let me check

**Comment by mmolhoek** [comment]
well, just use my two patches 
97c897b  and 
24a1329

**Comment by mmolhoek** [comment]
and you need to change the parameters from the test part at the end of edp.rb

`canvas = Papiruby::EPD.new({width:264, height: 176})`

to

`canvas = Papiruby::EPD.new()`

as you have the 2.0 display, which is the default values

**Comment by mmolhoek** [comment]
let me know what you think :)

**Comment by mmolhoek** [comment]
and maybe wait with adding stuff a I intent to get this [gem](https://github.com/mmolhoek/papirus) to work :)

**Comment by EddWills95** [comment]
Just having a look over your image.rb

Done a cracking job with getting the bits set up.

**Comment by mmolhoek** [comment]
Thanks,

but I got some help with the bits from the guy that made the chunky_png
library ;)

Anyway, I want to create a library that can work independently of chunky,
so you can shooed to use image magick if you wish, that's why I started my
own gem.

I'll let you know when it's usable ;)

I saw you tried to make your library work by letting it call the python
scripts. I am not sure if that is the right approach tough as the you add
shell creation overhead and basically your could better use python directly

Anyway, just my thoughts;)

**Comment by EddWills95** [comment]
I Think thats a much better approach, to not have the dependancy on them

Yeah that was my initial play with it, just to let ruby talk to it.
But the overhead as you say makes it a bit silly to bother. 

I'll keep checking back on yours as you progress and see if I can help at all

Edd. 



On Oct 05, 2017, at 08:17 AM, Mischa Molhoek <notifications@github.com> wrote:

Thanks,

but I got some help with the bits from the guy that made the chunky_png
library ;)

Anyway, I want to create a library that can work independently of chunky,
so you can shooed to use image magick if you wish, that's why I started my
own gem.

I'll let you know when it's usable ;)

I saw you tried to make your library work by letting it call the python
scripts. I am not sure if that is the right approach tough as the you add
shell creation overhead and basically your could better use python directly

Anyway, just my thoughts;)

**Comment by mmolhoek** [comment]
Hi @EddWills95,

The gem is available now. needs more work of course, but the base is working.

`gem install papirus`

see docu on [github](https://github.com/mmolhoek/papirus)

**Comment by mmolhoek** [comment]
updated my repo with explanation on how to use it with rmagick
and made the gem independant of chucky_png :)

**Comment by EddWills95** [comment]
You’ve done a brilliant job with this one. 

I started it with the best of intention but ended up with little spare time with work. 
The ultimate goal was to use it alongside a small rails app and now I think  this is totally possible. 


The next step is text I guess. We’ll have to create a canvas or sorts and then go through the process of converting it to bits. 

Really great Job :)

**Comment by mmolhoek** [comment]
Thanks :)

I am playing with rmagick at the moment to see how that performs

Just create a PR if you want to change or add anything :)

greetings,

Mischa

**Comment by mmolhoek** [comment]
HI @EddWills95 , just bumped [papirus](https://github.com/mmolhoek/papirus) to 0.3.1
it now has support for loading any type of image with Image Magick

grtz and have a great weekend!

**Pull request merged**
